#!/bin/zsh

# Set toml filename
TOML_FILE="~/.config/chezmoi/chezmoi.toml"
TIMESTAMP=$(date +%Y-%m-%d$Y-%H%M%S)

# Install oh-my-sh
install_ohmyzsh() {
  echo "backing up .oh-my-zsh"
  if [ -d ~/.oh-my-zsh ]; then
    mv ~/.oh-my-zsh ~/.oh-my-zsh-${TIMESTAMP}
  fi

  echo "Installing oh-my-zsh..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
}
install_ohmyzsh

# Update dot files
refresh_dot_files() {
  echo "Applying dotfiles with chezmoi ..."
  chezmoi init --apply --verbose https://github.com/jonnnylingo/dotfiles.git
  chmod 0600 "$HOME/.config/chezmoi/chezmoi.toml"
}

if [ -f ${TOML_FILE} ]; then
  echo "Backing up .config/chezmoi/chezmoi.toml"
  mv ${TOML_FILE} ${TOML_FILE}-${TIMESTAMP}
else
  brew install chezmoi
fi
refresh_dot_files
