#!/bin/zsh

# Set toml filename
TOML_FILE="$HOME/.config/chezmoi/chezmoi.toml"
TIMESTAMP=$(date +%Y-%m-%d$Y-%H%M%S)

# Make it happen
refresh_dot_files() {
  echo "Applying dotfiles with chezmoi ..."
  chezmoi init --apply --verbose https://github.com/jonnnylingo/dotfiles.git
  chmod 0600 "$HOME/.config/chezmoi/chezmoi.toml"
  source ~/.zshrc
}

if [ -f ${TOML_FILE} ]; then
  echo "Backing up .config/chezmoi/chezmoi.toml"
  mv ${TOML_FILE} ${TOML_FILE}-${TIMESTAMP}
else
  brew install chezmoi
fi

# Make fresh copy of dot_files
refresh_dot_files

#install oh-my-zsh
echo "backing up .oh-my-zsh"
if [ -d ~/.oh-my-zsh ]; then
  mv ~/.oh-my-zsh ~/.oh-my-zsh-${TIMESTAMP}
fi



echo "sourcing .zshrc"
sh -c '(echo "source .bashrc" >> ~/.zshrc)'
